include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.config.dart"

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false